// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyChFBA6TNF91PnNz1BmmJlrN3xor9CCENc',
    appId: '1:179638660806:web:f3073e755439c1161e31c7',
    messagingSenderId: '179638660806',
    projectId: 'hommie-b7459',
    authDomain: 'hommie-b7459.firebaseapp.com',
    storageBucket: 'hommie-b7459.appspot.com',
    measurementId: 'G-B3JL0LM1YL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdNSCWLcwl8AsFbukFq76Lb4p0npkULCE',
    appId: '1:179638660806:android:fd73ab20943f15561e31c7',
    messagingSenderId: '179638660806',
    projectId: 'hommie-b7459',
    storageBucket: 'hommie-b7459.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCYv-W1zq2QxagSZS1D5WNsLgu0ICodX4Q',
    appId: '1:179638660806:ios:ddc3990e421b2a5c1e31c7',
    messagingSenderId: '179638660806',
    projectId: 'hommie-b7459',
    storageBucket: 'hommie-b7459.appspot.com',
    androidClientId: '179638660806-7j4q9mktvf8q45psdl3oe3a3h9vg0jca.apps.googleusercontent.com',
    iosClientId: '179638660806-n3hmk5q0vm8vl8rvdhmkk4u3vknlumuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.hommie',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCYv-W1zq2QxagSZS1D5WNsLgu0ICodX4Q',
    appId: '1:179638660806:ios:ddc3990e421b2a5c1e31c7',
    messagingSenderId: '179638660806',
    projectId: 'hommie-b7459',
    storageBucket: 'hommie-b7459.appspot.com',
    androidClientId: '179638660806-7j4q9mktvf8q45psdl3oe3a3h9vg0jca.apps.googleusercontent.com',
    iosClientId: '179638660806-n3hmk5q0vm8vl8rvdhmkk4u3vknlumuf.apps.googleusercontent.com',
    iosBundleId: 'com.example.hommie',
  );
}
